version: '3.3'
 
services:
   wordpress:
     image: wordpress:latest
     container_name: roadmap-beginner-template
     depends_on:
       - db
     ports:
       - "5555:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - ./wordpress:/var/www/html
 
   db:
     image: mysql:5.7
     container_name: roadmap-beginner-template_mysql
     ports:
      - "8080:3306"
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       
volumes:
    db_data: